### ISSUE TITLE
🎨 implement a front like in the design in README.md

### ISSUE THREAD

**Issue by nazariyv** [re-nft/landing-page#1]
In terms of the assets we have an adobe illustrator file from our designer, and that is all...
[210504_LandingPageOnly.ai.zip](https://github.com/re-nft/landing-page/files/6430855/210504_LandingPageOnly.ai.zip)

**Comment by nazariyv** [comment]
As per usual, please use Tailwindcss, since we have subscription for that. I will have to look into it to see how I can share the creds for it with you.

Btw, there is someone else who has been tinkering with our front-end. This is what they have managed to create thus far:
https://renft.illuday.com/

**Comment by Nickev123** [comment]
Eniko, please let me know if you have any questions or need further files from Luis (reNFT's designer).

Happy to provide and around to answer questions!

**Comment by eenagy** [comment]
All right, I will be on it. The layout is straightforward, the animation part will take some time, research, and see what works best.

**Comment by nazariyv** [comment]
closing this since we have dorg on it
